client_id = "697313e4bf2304b130ef336d8b97b04e"
name = "GG Pickleball"
application_url = "https://gg-pickleball-production-9f94.up.railway.app/admin/brand"
embedded = false

[webhooks]
api_version = "2026-04"

[[webhooks.subscriptions]]
compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
uri = "https://gg-pickleball-production-9f94.up.railway.app/api/webhooks/shopify/compliance"

[[webhooks.subscriptions]]
topics = ["orders/paid"]
uri = "https://gg-pickleball-production-9f94.up.railway.app/api/webhooks/shopify/order"
filter = "discount_codes.code:GG*"

[access_scopes]
scopes = "read_discounts,write_discounts,read_merchant_managed_fulfillment_orders,read_orders,read_third_party_fulfillment_orders"
optional_scopes = []

use_legacy_install_flow = false

[auth]
redirect_urls = ["https://gg-pickleball-production-9f94.up.railway.app/api/shopify/callback"]